@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{host}}
@contentType = application/json

@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-user
Content-type: {{contentType}}

{
  "email": "nacao@gmail.com",
  "password": "Manh1234@"
}

###

# Get search history
GET {{baseUrl}}/api/play-together/v1/search-histories
?content=
&isNew=true
&PageNumber=1
&PageSize=20
Content-Type: : {{contentType}}
Authorization: {{authToken}}


###

# Get order request (receiver order)
GET {{baseUrl}}/api/play-together/v1/users/orders/requests?isNew=true
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get order by Id
GET {{baseUrl}}/api/play-together/v1/orders/4d9bbf79-d116-49e4-9bfa-c70b880b1145
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Process order
PUT {{baseUrl}}/api/play-together/v1/users/orders/4d9bbf79-d116-49e4-9bfa-c70b880b1145/process
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "isAccept": true
}

###


# Finish order soon
PUT {{baseUrl}}/api/play-together/v1/orders/finish-soon/4d9bbf79-d116-49e4-9bfa-c70b880b1145
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "message": "Cho tui nghi som nha"
}

###

# Get all Transaction
GET {{baseUrl}}/api/play-together/v1/users/transactions
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all un active money
GET {{baseUrl}}/api/play-together/v1/users/un-active-balance?isNew=true
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Check to active money
PUT {{baseUrl}}/api/play-together/v1/users/un-active-balance
Content-type: {{contentType}}
Authorization: {{authToken}}

###







# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user skill
GET {{baseUrl}}/api/play-together/v1/users/14085799-aec5-41b5-9fd9-46aa9a773443/games
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user hobbies
GET {{baseUrl}}/api/play-together/v1/users/14085799-aec5-41b5-9fd9-46aa9a773443/hobbies
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get all users / Search users
GET {{baseUrl}}/api/play-together/v1/users/
?searchString=Xu ka
Content-Type: : {{contentType}}
Authorization: {{authToken}}

###

# Get all Games
GET {{baseUrl}}/api/play-together/v1/games
?name=
&isMostFavorite=false
&pageSize=50
&pageNumber=1
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all Ranks in game
GET {{baseUrl}}/api/play-together/v1/games/fc05342f-8bba-4ef1-a396-4c5ff499a240/ranks
content-type: {{contentType}}
Authorization: {{authToken}}

###

# Create game of User
POST {{baseUrl}}/api/play-together/v1/games-of-user
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "gameId": "6c211880-ecd9-4975-806e-237fe1bc4294",
  "rankId": "79487e53-d990-4e6e-a3de-19bf9c155e99"
}

###

# Create game of User
POST {{baseUrl}}/api/play-together/v1/games-of-user
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "gameId": "fc05342f-8bba-4ef1-a396-4c5ff499a240",
  "rankId": "e40da2b5-f438-42fe-b257-92419d617805"
}

###

# Create game of User
POST {{baseUrl}}/api/play-together/v1/games-of-user
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "gameId": "a22cc921-25ce-41b7-b9a4-23fcb6e0db89",
  "rankId": ""
}

###

# Create game of User
POST {{baseUrl}}/api/play-together/v1/games-of-user
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "gameId": "34c265fb-bd1a-480b-86dd-29733954f3cc",
  "rankId": ""
}

###

# Create game of Hobbies
POST {{baseUrl}}/api/play-together/v1/hobbies
content-type: {{contentType}}
Authorization: {{authToken}}

[
  {
    "gameId": "141e7262-3c64-4c1d-a9a2-f8f9c18ae499"
  },
  {
    "gameId": "246c453d-8595-4d44-818a-c4ce158670df"
  },
  {
    "gameId": "27be12d7-7add-4ed9-a4d2-2af1d1f948d7"
  },
  {
    "gameId": "2c7c6c41-b49b-46b2-a4a4-c899057ebc34"
  },
]

###

# Delete hobbies
DELETE {{baseUrl}}/api/play-together/v1/hobbies
content-type: {{contentType}}
Authorization: {{authToken}}

[
  {
    "hobbyId": "150c1e97-655c-4eb8-a133-43760db0dd29",
    "hobbyId": "2550c869-2a9b-4093-8763-4876ac667163",
    "hobbyId": "5bc8f198-9b77-47cb-bd3b-33e80df604c1"
  }
]

###


# Get a game of User
GET {{baseUrl}}/api/play-together/v1/games-of-user/2e2636c5-d20a-4989-a515-bb1be026b0f4
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Update game of User
PUT {{baseUrl}}/api/play-together/v1/games-of-user/2e2636c5-d20a-4989-a515-bb1be026b0f4
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "rankId": "400e56f9-a172-4012-9b86-74af5b6e2eed"
}

###

# Delete game of User
DELETE {{baseUrl}}/api/play-together/v1/games-of-user/2e2636c5-d20a-4989-a515-bb1be026b0f4
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Update user service
PUT {{baseUrl}}/api/play-together/v1/users/service
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "maxHourHire": 5,
  "pricePerHour": 10000.0
}

###