@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-admin
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}

###


# Get dash board
GET {{baseUrl}}/api/play-together/v1/admins/dash-board
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all users
GET {{baseUrl}}/api/play-together/v1/admins/users
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get reports of user
GET {{baseUrl}}/api/play-together/v1/reports/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###



# Get all reports
GET {{baseUrl}}/api/play-together/v1/admins/reports
?IsApprove=
&IsNew=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###


# Get a report in detail
GET {{baseUrl}}/api/play-together/v1/admins/reports/e3f92af3-5d1c-47b7-b86b-8883efaf90fe
Content-Type: {{contentType}}
Authorization: {{authToken}}

###


# Approve or Denied a report in detail
PUT {{baseUrl}}/api/play-together/v1/admins/reports/e3f92af3-5d1c-47b7-b86b-8883efaf90fe
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "isApprove": true,
  "point": 1,
  "satisfiedPoint": 1,
  "isDisableAccount": false
}
###



# Get all player rating violate
GET {{baseUrl}}/api/play-together/v1/rating/violates
?IsNew=true
&IsActive=false
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get a rating detail
GET {{baseUrl}}/api/play-together/v1/rating/detail/f2959786-3ae6-4cca-9f02-cb4dda88f65f
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Process violate rating
PUT {{baseUrl}}/api/play-together/v1/rating/process/f2959786-3ae6-4cca-9f02-cb4dda88f65f
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "isApprove": true
}
###


# Disable account
PUT {{baseUrl}}/api/play-together/v1/admins/hirer-status/2181af98-904a-4df9-9b9a-96bc925956ff
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "isActive" : false,
  "message" : "Sao bạn chửi player chơi ngu...."
}

###


# Get all orders of a specific Hirer
GET {{baseUrl}}/api/play-together/v1/admins/d04a4aa1-0f83-4acd-a645-f6aaae367154/orders?isNew=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get a order detail
GET {{baseUrl}}/api/play-together/v1/admins/users/orders/1c7a7c61-831d-478b-8bc0-4868160fda75
Content-Type: {{contentType}}
Authorization: {{authToken}}

###


# Get all Feedbacks 
GET {{baseUrl}}/api/play-together/v1/feedbacks
Content-type: {{contentType}}
Authorization: {{authToken}}


###


# Get a feedback
GET {{baseUrl}}/api/play-together/v1/feedbacks/408790d0-090e-42db-8985-78116c2bee1a
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Process feedback
PUT {{baseUrl}}/api/play-together/v1/admins/feedbacks/408790d0-090e-42db-8985-78116c2bee1a
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "isApprove": false
}

###


# Train model
GET {{baseUrl}}/api/play-together/v1/admins/train-model
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get all system config
GET {{baseUrl}}/api/play-together/v1/system-configs
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Creat a system config
POST {{baseUrl}}/api/play-together/v1/system-configs
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "title": "Order Process Expire Time",
  "nO": 1,
  "value": 5
}


###

# Delete systemconfig
DELETE  {{baseUrl}}/api/play-together/v1/system-configs/1a7ca621-4e0f-4e1f-ac82-0ecf06f22e4a
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get system config by NO
GET {{baseUrl}}/api/play-together/v1/system-configs/no-1
Content-type: {{contentType}}
Authorization: {{authToken}}

###