@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/account/login
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}

###
# Get all charities
GET {{baseUrl}}/api/play-together/v1/charities
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get all charities with paging, search
GET {{baseUrl}}/api/play-together/v1/charities
    ?Name=a
    &PageNumber=1
    &PageSize=10
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get a charity by Id
GET {{baseUrl}}/api/play-together/v1/charities/
content-type: {{contentType}}
Authorization: {{authToken}}