@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{lchost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login
content-type: {{contentType}}

{
  "email": "tienphong123@example.com",
  "password": "Pa55w0rd!"
}

###
# Get all charities
GET {{baseUrl}}/api/play-together/v1/charities
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get all charities with paging, search
GET {{baseUrl}}/api/play-together/v1/charities
    ?Name=
    &PageNumber=
    &PageSize=
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get a charity by Id
GET {{baseUrl}}/api/play-together/v1/charities/
content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get number of donate in today
GET {{baseUrl}}/api/play-together/v1/charities/number-of-donate
?IsCalculateNumberOfDonateInDate=true
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all charity Notification
GET {{baseUrl}}/api/play-together/v1/notification?IsNew=true
Content-Type: {{contentType}}
Authorization: {{authToken}}