@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/auth/login
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}


###
# Get all game type
GET {{baseUrl}}/api/play-together/v1/gametypes
content-type: {{contentType}}
Authorization: {{authToken}}


###
# Get all game type with search
GET {{baseUrl}}/api/play-together/v1/gametypes
  ?name=mo
content-type: {{contentType}}
Authorization: {{authToken}}


###
# Create a new game type
POST {{baseUrl}}/api/play-together/v1/gametypes
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "typeName": "FPS"
}

###
# Get by Id
GET {{baseUrl}}/api/play-together/v1/gametypes/1c880885-0409-4466-91f7-9ef908639548
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Update game type
PUT {{baseUrl}}/api/play-together/v1/gametypes/44e7bb53-0158-4e94-bb31-cdf617698b4a
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "typeName": "Puzzle"
}

###
# Delete
DELETE {{baseUrl}}/api/play-together/v1/gametypes/01f5a4e8-cd3f-4a2e-ba85-7f082f3a744e
content-type: {{contentType}}
Authorization: {{authToken}}