@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-admin
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}

###


# Get all Games
GET {{baseUrl}}/api/play-together/v1/games
?pageSize=10
&pageNumber=1
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all Ranks in game
GET {{baseUrl}}/api/play-together/v1/games/7c35408c-7988-4f3b-8479-6822cb222d77/ranks
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create a new rank in game
POST {{baseUrl}}/api/play-together/v1/games/89592649-2bba-4d06-9443-50867ffac6da/ranks
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "no": 3,
  "name": "Bạch Kim"
}

###



# Get all Games
GET {{baseUrl}}/api/play-together/v1/games
?name=lol
content-type: {{contentType}}
Authorization: {{authToken}}


###




# Get Game by Id
GET {{baseUrl}}/api/play-together/v1/games/dbbda087-30e5-4561-be36-e4513f9ca387
content-type: {{contentType}}
Authorization: {{authToken}}

###



# Create a new game
POST {{baseUrl}}/api/play-together/v1/games
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Tafo lao",
  "displayName": "Tafo lao",
  "otherName": "string"
}

###




# Update a game
PUT {{baseUrl}}/api/play-together/v1/games/33a8029b-e121-4f5f-8d97-50039a1fb110
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "CSGO",
  "displayName": "Liên Minh Huyền Thoại",
  "otherName": "Liên minh / lol / lien minh"
}

###




# Delete a game
DELETE {{baseUrl}}/api/play-together/v1/games/75fb7522-48c3-4ed7-9089-e84ce05dd9cd
content-type: {{contentType}}
Authorization: {{authToken}}