@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}


###
# Get all Games
GET {{baseUrl}}/api/play-together/v1/games
?pageSize=100
&pageNumber=1
content-type: {{contentType}}
Authorization: {{authToken}}


###
# Get all Ranks in game
GET {{baseUrl}}/api/play-together/v1/games/dbbda087-30e5-4561-be36-e4513f9ca387/ranks
content-type: {{contentType}}
Authorization: {{authToken}}


###
# Create a new rank in game
POST {{baseUrl}}/api/play-together/v1/games/7caacf43-a337-4df0-b4bf-f1e07a37fe7e/ranks
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "no": 8,
  "name": "Thách Đấu"
}

###



# Get all Games
GET {{baseUrl}}/api/play-together/v1/games
  ?name= lien
content-type: {{contentType}}
Authorization: {{authToken}}


###




# Get Game by Id
GET {{baseUrl}}/api/play-together/v1/games/dbbda087-30e5-4561-be36-e4513f9ca387
content-type: {{contentType}}
Authorization: {{authToken}}

###



# Create a new game
POST {{baseUrl}}/api/play-together/v1/games
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "CSGO",
  "displayName": ""
}

###




# Update a game
PUT {{baseUrl}}/api/play-together/v1/games/dbbda087-30e5-4561-be36-e4513f9ca387
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "League Of Legends",
  "displayName": "Liên Minh Huyền Thoại",
  "otherName": "Liên minh / lol / lien minh"
}

###




# Delete a game
DELETE {{baseUrl}}/api/play-together/v1/games/310c8cf1-053a-40f7-b5eb-bfaca7c96ac3
content-type: {{contentType}}
Authorization: {{authToken}}