@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-admin
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}


###
# Get all game type
GET {{baseUrl}}/api/play-together/v1/game-types
content-type: {{contentType}}
Authorization: {{authToken}}


###
# Get all game type with search
GET {{baseUrl}}/api/play-together/v1/game-types
?name=hành động
content-type: {{contentType}}
Authorization: {{authToken}}


###
# Create a new game type
POST {{baseUrl}}/api/play-together/v1/game-types
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "string",
  "shortName": "string",
  "otherName": "string",
  "description": "string"
}

###
# Get by Id
GET {{baseUrl}}/api/play-together/v1/game-types/f3fde2b6-941c-4763-b39a-fd833f47dbf9
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Update game type
PUT {{baseUrl}}/api/play-together/v1/game-types/f3fde2b6-941c-4763-b39a-fd833f47dbf9
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "string",
  "shortName": "asdfsda",
  "otherName": "strvvvving",
  "description": "string"
}

###
# Delete
DELETE {{baseUrl}}/api/play-together/v1/game-types/f3fde2b6-941c-4763-b39a-fd833f47dbf9
content-type: {{contentType}}
Authorization: {{authToken}}