@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json

@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login
content-type: {{contentType}}

{
  "email": "hirer01@example.com",
  "password": "Pa55w0rd!"
}

###
# Get Hirer Profile
GET {{baseUrl}}/api/play-together/v1/hirers/profile
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get Hirer by Id
GET {{baseUrl}}/api/play-together/v1/hirers/d971f853-b95b-4e62-911c-106d2e5cb14c
content-type: {{contentType}}
Authorization: {{authToken}}

### Update Hirer Profile by Id
PUT {{baseUrl}}/api/play-together/v1/hirers/d36ded19-c738-472a-845e-6fd9c88dc3de
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "firstname": "Hao",
  "lastname": "Nguyen Nhut",
  "city": "Long An Province",
  "dateOfBirth": "2000-01-01",
  "gender": true,
  "avatar": ""
}

###
# Get all players
GET {{baseUrl}}/api/play-together/v1.1/players
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get all players with paging, filter, search
GET {{baseUrl}}/api/play-together/v1.1/players
    ?SearchString=tham
    &Gender=
    &IsRecent=
    &GameId=
    &MusicId=
    &PlayerStatus=
    &IsOrderByFirstName=
    &IsOrderByRating=
    &IsOrderByPricing=
    &PageNumber=1
    &PageSize=10
content-type: {{contentType}}
Authorization: {{authToken}}


### 
# Get Player by Id for hirer
GET {{baseUrl}}/api/play-together/v1.1/players/b2c7ff4f-d487-4920-b250-5ac5687d964b
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Get all hirer orders
GET {{baseUrl}}/api/play-together/v1/hirers/orders?IsNew=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
# Create Order to player
POST {{baseUrl}}/api/play-together/v1/hirers/orders/250282e3-e053-4825-af00-e6bc2f908b51
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "totalTimes": 1,
  "message": "Bạn ơi chơi game lol vs mình không"
}

###
# Get order by Id
GET {{baseUrl}}/api/play-together/v1/orders/7e591c17-b30a-4a34-8da8-b6ecba4a73a2
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
# Cancel order request
PUT {{baseUrl}}/api/play-together/v1/hirers/cancel/orders/d133688b-d9cb-4014-878d-69d400216d57
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
# Finish order
PUT {{baseUrl}}/api/play-together/v1/orders/finish/8d607da0-0cfa-4b5d-b36a-901687b4411d
Content-Type: {{contentType}}
Authorization: {{authToken}}

###


# Finish soon order
PUT {{baseUrl}}/api/play-together/v1/orders/finish-soon/fe0ff712-e9be-44cd-9ff3-0049fafe8a26
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "message" : "Mình bận đột xuất, cám ơn bạn đã thông cảm...:))"
}

###



# Get all Hirer Notification
GET {{baseUrl}}/api/play-together/v1/notification?IsNew=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get a Notification
GET {{baseUrl}}/api/play-together/v1/notification/fa0a67b3-076b-41d8-ab56-56494b91f761
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get Notification in detail
GET {{baseUrl}}/api/play-together/v1/notification/ec479d05-bf73-4fe3-b072-b26967b231ab
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Rate 
POST {{baseUrl}}/api/play-together/v1/rating/fe0ff712-e9be-44cd-9ff3-0049fafe8a26
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "comment": "Danh hay quá....",
  "rate": 5
}

###

# Get all report of a hirer
GET {{baseUrl}}/api/play-together/v1/reports/2181af98-904a-4df9-9b9a-96bc925956ff
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Create chat message
POST {{baseUrl}}/api/play-together/v1/chats/49697e13-a64b-478b-8551-00f6571fdf47
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "message": "Bạn tên gì...."
}

###

# Get alls chat message
GET {{baseUrl}}/api/play-together/v1/chats/49697e13-a64b-478b-8551-00f6571fdf47
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Delete a chat message
DELETE {{baseUrl}}/api/play-together/v1/chats/07518d39-5e72-44fa-b054-54ea0ce7c62c
Content-Type: {{contentType}}
Authorization: {{authToken}}

###