@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json

@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}



# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-user
Content-type: {{contentType}}

{
  "email": "hien@example.com",
  "password": "Pa55w0rd!"
}

###


# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get all users / Search users
GET {{baseUrl}}/api/play-together/v1/users/
?search=tham
Content-Type: : {{contentType}}
Authorization: {{authToken}}

###

# Get search history
GET {{baseUrl}}/api/play-together/v1/search-histories
?isNew=true
Content-Type: : {{contentType}}
Authorization: {{authToken}}


###

# Get user basic information
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user skill information
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c/games
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user by Id
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user service information
GET {{baseUrl}}/api/play-together/v1/users/service/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create order
POST {{baseUrl}}/api/play-together/v1/users/orders/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "totalTimes": 4,
  "message": "Choi lol ko ban ơi",
  "games": [
    {
      "gameId": "7c35408c-7988-4f3b-8479-6822cb222d77"
    }
  ]
}

###

# Get all order (create User)
GET {{baseUrl}}/api/play-together/v1/users/orders?isNew=true
Content-type: {{contentType}}
Authorization: {{authToken}}

###



# Get a order
GET {{baseUrl}}/api/play-together/v1/orders/b5dc273e-87f3-4d79-a745-56326a16f5df
Content-type: {{contentType}}
Authorization: {{authToken}}

###



# Cancel order
PUT {{baseUrl}}/api/play-together/v1/users/orders/cancel/b5dc273e-87f3-4d79-a745-56326a16f5df
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get Notification
GET {{baseUrl}}/api/play-together/v1/notification?isNew=true
Content-type: {{contentType}}
Authorization: {{authToken}}


###

# Get Notification
GET {{baseUrl}}/api/play-together/v1/notification/309d1238-81d1-45e6-a37f-9dc134b1311c
Content-type: {{contentType}}
Authorization: {{authToken}}


###

# Get all Transaction
GET {{baseUrl}}/api/play-together/v1/users/transactions?isNew=true
&Type=order
&Operation="+"
Content-type: {{contentType}}
Authorization: {{authToken}}


###

# Create rating
POST {{baseUrl}}/api/play-together/v1/rating/3f266f34-1d61-4a56-bb74-6aa5912750eb
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "comment": "Cups sowm quassss",
  "rate": 1
}

###


# Create report
POST {{baseUrl}}/api/play-together/v1/reports/d7503c35-fa0c-4727-98ff-84ad64da81c5
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "reportMessage": "Bỏ giữa chừng..."
}

###


# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Chat
GET {{baseUrl}}/api/play-together/v1/chats/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create chat
POST {{baseUrl}}/api/play-together/v1/chats/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "message": "Thật ko v..."
}

###

# Delete chat
DELETE {{baseUrl}}/api/play-together/v1/chats/{chatId}
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create donate
POST {{baseUrl}}/api/play-together/v1/donates/
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all Feedbacks 
GET {{baseUrl}}/api/play-together/v1/feedbacks
Content-type: {{contentType}}
Authorization: {{authToken}}


###


# Get a feedback
GET {{baseUrl}}/api/play-together/v1/feedbacks/d05fbc3a-9865-4aa4-a823-c67ef7d330d9
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Create Feedback
POST {{baseUrl}}/api/play-together/v1/feedbacks
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "title": "Test Feedback",
  "message": "Test chuc nang feedback...",
  "typeOfFeedback": "Test"
}

###


# Update Feedback
PUT {{baseUrl}}/api/play-together/v1/feedbacks/d05fbc3a-9865-4aa4-a823-c67ef7d330d9
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "title": "Test Feedback",
  "message": "Test chuc nang feedback..aaaaaaaaa.",
  "typeOfFeedback": "Test"
}

###

# Delete Feedback
DELETE {{baseUrl}}/api/play-together/v1/feedbacks/d05fbc3a-9865-4aa4-a823-c67ef7d330d9
Content-type: {{contentType}}
Authorization: {{authToken}}

###




# Train model
GET {{baseUrl}}/api/play-together/v1/users/train-model
Content-type: {{contentType}}
Authorization: {{authToken}}

###