@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json

@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}



# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-user
Content-type: {{contentType}}

{
  "email": "hien@example.com",
  "password": "Pa55w0rd!"
}

###


# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user behavior point information
GET {{baseUrl}}/api/play-together/v1/users/d04a4aa1-0f83-4acd-a645-f6aaae367154/behavior-point
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user balance information
GET {{baseUrl}}/api/play-together/v1/users/d04a4aa1-0f83-4acd-a645-f6aaae367154/balance
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/d04a4aa1-0f83-4acd-a645-f6aaae367154/hobbies
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get all users / Search users
GET {{baseUrl}}/api/play-together/v1/users/
?IsOrderByRating=true
Content-Type: : {{contentType}}
Authorization: {{authToken}}

###

# Update ranking point
PUT {{baseUrl}}/api/play-together/v1/users/update-ranking
Content-Type: : {{contentType}}
Authorization: {{authToken}}

###

# Get search history
GET {{baseUrl}}/api/play-together/v1/search-histories
?content=
&isNew=true
&PageNumber=1
&PageSize=20
Content-Type: : {{contentType}}
Authorization: {{authToken}}


###

# Get search history
GET {{baseUrl}}/api/play-together/v1/search-histories
?isHotSearch=true
Content-Type: : {{contentType}}
Authorization: {{authToken}}


###

# Get user basic information
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user skill information
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c/games
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get reports of user
GET {{baseUrl}}/api/play-together/v1/reports/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get user by Id
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user service information
GET {{baseUrl}}/api/play-together/v1/users/service/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create order
POST {{baseUrl}}/api/play-together/v1/users/orders/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "totalTimes": 1,
  "message": "Choi lol ko ban ơi",
  "games": [
    {
      "gameId": "7c35408c-7988-4f3b-8479-6822cb222d77"
    }
  ]
}

###

# Get all order (create User)
GET {{baseUrl}}/api/play-together/v1/users/orders?isNew=true
Content-type: {{contentType}}
Authorization: {{authToken}}

###



# Get a order
GET {{baseUrl}}/api/play-together/v1/orders/b5dc273e-87f3-4d79-a745-56326a16f5df
Content-type: {{contentType}}
Authorization: {{authToken}}

###



# Cancel order
PUT {{baseUrl}}/api/play-together/v1/users/orders/cancel/b5dc273e-87f3-4d79-a745-56326a16f5df
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Finish order soon
PUT {{baseUrl}}/api/play-together/v1/orders/finish-soon/91678b9b-75ce-47b4-9a0c-3aff98ee6754
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "reason": "Nghi ddi banj oiw....tui trau law...."
}

###


# Get Notification
GET {{baseUrl}}/api/play-together/v1/notification?isNew=true
Content-type: {{contentType}}
Authorization: {{authToken}}


###

# Get Notification
GET {{baseUrl}}/api/play-together/v1/notification/309d1238-81d1-45e6-a37f-9dc134b1311c
Content-type: {{contentType}}
Authorization: {{authToken}}


###

# Get all Transaction
GET {{baseUrl}}/api/play-together/v1/users/transactions?isNew=true
&Type=order
&Operation="+"
Content-type: {{contentType}}
Authorization: {{authToken}}


###

# Create rating
POST {{baseUrl}}/api/play-together/v1/rating/91678b9b-75ce-47b4-9a0c-3aff98ee6754
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "comment": "Cups sowm quassss, dcmmmmmmm",
  "rate": 1
}

###


# Create report
POST {{baseUrl}}/api/play-together/v1/reports/57c9e597-326c-482c-8e9c-9feedc34dfff
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "reportMessage": "Bỏ giữa chừng...banj test tis "
}

###


# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Chat
GET {{baseUrl}}/api/play-together/v1/chats/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create chat
POST {{baseUrl}}/api/play-together/v1/chats/a17bd7c6-0fcc-48ea-89de-43823a1ec09c
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "message": "Thật ko v..."
}

###

# Delete chat
DELETE {{baseUrl}}/api/play-together/v1/chats/{chatId}
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create donate
POST {{baseUrl}}/api/play-together/v1/donates/
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Get all Feedbacks 
GET {{baseUrl}}/api/play-together/v1/feedbacks
?fromDate=2022-04-10
&toDate=2022-05-10
Content-type: {{contentType}}
Authorization: {{authToken}}


###


# Get a feedback
GET {{baseUrl}}/api/play-together/v1/feedbacks/408790d0-090e-42db-8985-78116c2bee1a
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Create Feedback
POST {{baseUrl}}/api/play-together/v1/feedbacks
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "title": "Test Feedback again",
  "message": "Test chuc nang feedback..Vui long thong camr.",
  "typeOfFeedback": "Suggest"
}

###


# Update Feedback
PUT {{baseUrl}}/api/play-together/v1/feedbacks/408790d0-090e-42db-8985-78116c2bee1a
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "title": "Test Feedback",
  "message": "Test chuc nang feedback..aaaaaaaaa.",
  "typeOfFeedback": "Test"
}

###

# Delete Feedback
DELETE {{baseUrl}}/api/play-together/v1/feedbacks/408790d0-090e-42db-8985-78116c2bee1a
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###


# Create Dating
POST {{baseUrl}}/api/play-together/v1/dating
Content-type: {{contentType}}
Authorization: {{authToken}}

{
  "fromHour": 17,
  "toHour": 19,
  "dayInWeek": 3
}

###

# Delete Dating
DELETE {{baseUrl}}/api/play-together/v1/dating/ca0c8bbb-3960-4c1c-ab91-d105cd908226
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user personal information
GET {{baseUrl}}/api/play-together/v1/users/personal
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user skill
GET {{baseUrl}}/api/play-together/v1/users/14085799-aec5-41b5-9fd9-46aa9a773443/games
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get user hobbies
GET {{baseUrl}}/api/play-together/v1/users/d04a4aa1-0f83-4acd-a645-f6aaae367154/hobbies
Content-type: {{contentType}}
Authorization: {{authToken}}

###

# Get all users / Search users
GET {{baseUrl}}/api/play-together/v1/users/
?searchString=th
Content-Type: : {{contentType}}
Authorization: {{authToken}}

###

# Get all Games
GET {{baseUrl}}/api/play-together/v1/games
?name=
&isMostFavorite=false
&pageSize=50
&pageNumber=1
content-type: {{contentType}}
Authorization: {{authToken}}

###

# Create game of Hobbies
POST {{baseUrl}}/api/play-together/v1/hobbies
content-type: {{contentType}}
Authorization: {{authToken}}

[
  {
    "gameId": "11614602-3a32-4901-821f-9cfc36a006ec"
  },
  {
    "gameId": "2e52cd92-cf0a-4499-aa96-b1fa0d3dcc23"
  },
  {
    "gameId": "2eeecd82-49c3-4cc6-b238-39c3f67660a9"
  },
  {
    "gameId": "2f07e88a-8874-4898-b356-02f40bdb54e5"
  },
]

###

# Delete hobbies
DELETE {{baseUrl}}/api/play-together/v1/hobbies
content-type: {{contentType}}
Authorization: {{authToken}}

[
  {
    "hobbyId": "baa835c4-b4ba-4f9e-8213-9bb74c30cf86"
  },
  {
    "hobbyId": "2e56f572-8845-442d-bc98-c565fd4bad17"
  }
]

###


# Dating
GET {{baseUrl}}/api/play-together/v1/users/d04a4aa1-0f83-4acd-a645-f6aaae367154/datings
content-type: {{contentType}}
Authorization: {{authToken}}

###

# Rating
GET {{baseUrl}}/api/play-together/v1/users/a17bd7c6-0fcc-48ea-89de-43823a1ec09c/ratings
content-type: {{contentType}}
Authorization: {{authToken}}

###