@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/auth/login
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}

###
# Get rank by Id
GET {{baseUrl}}/api/play-together/v1/ranks/8d1557f0-0cf1-44d1-bed5-3b3bc512e1d1
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Update rank
PUT {{baseUrl}}/api/play-together/v1/ranks/5d37a5fe-dfa2-4a44-8f33-5255e1a26ae3
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Bạch Kim"
}

###
# Delete rank by Id
DELETE {{baseUrl}}/api/play-together/v1/ranks/8d1557f0-0cf1-44d1-bed5-3b3bc512e1d1
content-type: {{contentType}}
Authorization: {{authToken}}

