@hostname = localhost
@port = 5001
@azurehost = play-together.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{lchost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

###
# @name login
POST {{baseUrl}}/api/play-together/v1/accounts/login-admin
content-type: {{contentType}}

{
  "email": "admin01@example.com",
  "password": "Pa55w0rd!"
}

###
# Get rank by Id
GET {{baseUrl}}/api/play-together/v1/ranks/ec006e5f-b4aa-48a2-bee6-bcbd6e9ef444
content-type: {{contentType}}
Authorization: {{authToken}}

###
# Update rank
PUT {{baseUrl}}/api/play-together/v1/ranks/ec006e5f-b4aa-48a2-bee6-bcbd6e9ef444
content-type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Bạch Kim"
}

###
# Delete rank by Id
DELETE {{baseUrl}}/api/play-together/v1/ranks/9b1e65b9-4664-4cb1-9b0c-c3249aaf1dd2
content-type: {{contentType}}
Authorization: {{authToken}}

